repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: vaultmesh-make-check
        name: vaultmesh make check
        entry: make check
        language: system
        pass_filenames: false
      - id: vaultmesh-prompts-lint
        name: vaultmesh prompts lint
        entry: make prompts:lint
        language: system
        pass_filenames: false
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint-cli2.yaml", "docs/**/*.md"]
        stages: [commit]
